// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjNfY_PfrEHchQ_IBKWMBZwfZWKUFxzU',
    appId: '1:810991594594:web:8fd883f8b5f7f53030753b',
    messagingSenderId: '810991594594',
    projectId: 'turning-point-tms',
    authDomain: 'turning-point-tms.firebaseapp.com',
    storageBucket: 'turning-point-tms.appspot.com',
    measurementId: 'G-5Z8DX85HY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHYEXztT4nbeE0fAqoCESfnat84686NE',
    appId: '1:810991594594:android:9cfa22f8b09ea7bc30753b',
    messagingSenderId: '810991594594',
    projectId: 'turning-point-tms',
    storageBucket: 'turning-point-tms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZLaNVft2GIXzSDRp5StS5Bo7xWQU0ow',
    appId: '1:810991594594:ios:bc4146106eb3b36a30753b',
    messagingSenderId: '810991594594',
    projectId: 'turning-point-tms',
    storageBucket: 'turning-point-tms.firebasestorage.app',
    iosBundleId: 'com.example.turningPointTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZLaNVft2GIXzSDRp5StS5Bo7xWQU0ow',
    appId: '1:810991594594:ios:bc4146106eb3b36a30753b',
    messagingSenderId: '810991594594',
    projectId: 'turning-point-tms',
    storageBucket: 'turning-point-tms.appspot.com',
    iosBundleId: 'com.example.turningPointTasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjNfY_PfrEHchQ_IBKWMBZwfZWKUFxzU',
    appId: '1:810991594594:web:ffb788011c8f8d3330753b',
    messagingSenderId: '810991594594',
    projectId: 'turning-point-tms',
    authDomain: 'turning-point-tms.firebaseapp.com',
    storageBucket: 'turning-point-tms.appspot.com',
    measurementId: 'G-06NNY24YRB',
  );
}